//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkiTakipSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personels()
        {
            this.Works = new HashSet<Works>();
        }
    
        public int PersonelId { get; set; }
        public string PersonelAdSoyad { get; set; }
        public string PersonelKullaniciAd { get; set; }
        public string PersonelParola { get; set; }
        public Nullable<int> PersonelLocationId { get; set; }
        public Nullable<int> PersonelAuthorizationId { get; set; }
    
        public virtual AuthorizationTypes AuthorizationTypes { get; set; }
        public virtual Locations Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Works> Works { get; set; }
    }
}
