//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkiTakipSystemMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlantTakipDbEntities : DbContext
    {
        public PlantTakipDbEntities()
            : base("name=PlantTakipDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorizationTypes> AuthorizationTypes { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Personels> Personels { get; set; }
        public virtual DbSet<Progress> Progress { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Works> Works { get; set; }
    }
}
