//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkiTakipSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public int worksId { get; set; }
        public string workName { get; set; }
        public string workAciklama { get; set; }
        public Nullable<int> workfarmerId { get; set; }
        public Nullable<System.DateTime> iletilenTarih { get; set; }
        public Nullable<System.DateTime> yapilanTarih { get; set; }
        public Nullable<int> workprogressId { get; set; }
    
        public virtual Personels Personels { get; set; }
        public virtual Progress Progress { get; set; }
    }
}
